# -*- coding: utf-8 -*-
"""면역반응 프로토타입.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Robffivhquq1uWOpUUaRSRx14ZPrByrz

# 백혈구의 수명에 따른 바이러스에서의 생존률
"""

import numpy as np
import random as rand
import matplotlib as mlp
import seaborn as sns

'''
Done : 프로토타입 구현 - 바이러스, 백혈구 개체 수 지정, 확률적으로 면역반응 성립, 리스트생성(면역반응 수, 살아남은 바이러스 수, 살아남은 백혈구 수 / 죽은 횟수, 살아남은 횟수)
To do : 바이러스와 백혈구 증식 시스템 구현, 실제 백혈구 메커니즘 어느 정도 구현
Will do : 항체가 관여하는 면역 시스템 구현, 백혈구과다증 구현, 오류 수정정
'''

#변수 지정
virus = 1000
leukocyte = 1000
dis = 0
count = 0
death = 0
alive = 0
WBC = leukocyte
#리스트 생성
cnt = list()
vir = list()
b = list()

#range횟수만큼 반복
for i in range(100):

  #while문 내부에서 변화한 변수 값 초기화
  virus = 100000
  WBC = 100
  count = 0

  #바이러스나 백혈구가 0이 될 때까지 반복
  while(virus>0) & (WBC!=0):
    virus = virus - WBC*50
   
    if count%3 == 0:  #3일 마다 백혈구 증식        
       WBC = 2*WBC
    if count%7 == 0:  #7일 마다 바이러스 증식
       virus = 2*virus
    if count%5 == 0:  #5일 마다 1%의 백혈구 사망망
       WBC = 0.99*WBC         
    count = count + 1
    if count > 10:
      break
  if(virus <= 0):
    alive = alive + 1
  else:
    death = death + 1

  #while문 종료 후 값 저장
  cnt.append(count)
  vir.append(virus)
  b.append(WBC)

print(cnt,"\n", vir,"\n", b)
death,alive

